### ISSUE TITLE
License mismatch in PyPI

### ISSUE THREAD

**Issue by nrmisturakJPMC** [localstack/localstack-extensions#6]
I tried installing localstack version 1.0.4 from PyPI at work, however, it's blocked due to the  license of package localstack-ext being listed as "Other/Proprietary License (Proprietary)" on PyPI (https://pypi.org/project/localstack-ext/#description)

Within Github, it looks like the license is actually Apache 2.0, which my work would accept.  Is there any possibility PyPI could have the license listed for this package updated to Apache 2.0 as well?

**Comment by whummer** [comment]
Hi @nrmisturakJPMC , thanks for reaching out. Please note that this repository is about LocalStack Extensions (a plugin mechanism for developers to plug in new services or functionality into LocalStack), whereas the [https://pypi.org/project/localstack-ext](https://pypi.org/project/localstack-ext/#description) Pypi package contains the proprietary features for LocalStack Pro (the commercial version of LocalStack). 

If you're using the Community version of LocalStack, then the `localstack-ext` package is included in the dependencies (and the Docker image), but it doesn't actually get activated.

Hope that helps. Please feel free to reach out to info@localstack.cloud - we'll be happy to work with you to get this resolved, in case the issue still persists.. Thanks!
