### ISSUE TITLE
AWS Replicator: Error: No such command 'replicate'

### ISSUE THREAD

**Issue by well-it-wasnt-me** [localstack/localstack-extensions#60]
Hi, just followed the guide to the T.

After installing the aws-replicator extension and i lunch the command `localstack aws replicate -s sqs`

i receive the following error:

```
Usage: localstack aws [OPTIONS] COMMAND [ARGS]...
Try 'localstack aws -h' for help.

Error: No such command 'replicate'.
```

And when going to check the content of available commands for aws i get only this

```
Usage: localstack aws [OPTIONS] COMMAND [ARGS]...

  Accesses additional functionality on LocalStack emulated AWS services.

  This command provides tools to enhance your experience with certain emulated
  AWS services.

Options:
  -h, --help  Show this message and exit.

Commands:
  iam  (Beta) Access LocalStack IAM features

```

I am using a trial version of the Pro, LocalStack CLI 3.4.0

localstack status output

```
┌─────────────────┬───────────────────────────────────────────────────────┐
│ Runtime version │ 3.4.1.dev                                             │
│ Docker image    │ tag: latest, id: 4b87860f7f42, 📆 2024-05-06T13:49:55 │
│ Runtime status  │ ✔ running (name: "localstack-main", IP: 172.17.0.2)   │
└─────────────────┴───────────────────────────────────────────────────────┘

```

**Comment by derick1156** [comment]
I am experiencing the exact same issue

**Comment by well-it-wasnt-me** [comment]
@derick1156 inwrote myself a script that does this. Soon I'll publish it

**Comment by well-it-wasnt-me** [comment]
@derick1156 

https://github.com/well-it-wasnt-me/Import-AWS-To-Localstack

**Comment by whummer** [comment]
Thanks for reporting @well-it-wasnt-me @derick1156 , and apologies for the long delay here, this issue somehow slipped through the cracks. :/ 

We have made a couple of fixes to the extension in the meantime (there were some Python import errors) - when you get a chance, can you please give it another try installing it?

However, we have recently focusing mostly on the `proxy` mode of the extension, less so on the `replicate` mode (which still needs to be refactored/improved a bit in the upcoming weeks). Thanks for sharing the pointer to the external repo, we'll see if we can take some inspiration from it, to make sure the functionality is covered in this repo as well! 🙌

**Comment by well-it-wasnt-me** [comment]
> Thanks for reporting @well-it-wasnt-me @derick1156 , and apologies for the long delay here, this issue somehow slipped through the cracks. :/
> 
> We have made a couple of fixes to the extension in the meantime (there were some Python import errors) - when you get a chance, can you please give it another try installing it?
> 
> However, we have recently focusing mostly on the `proxy` mode of the extension, less so on the `replicate` mode (which still needs to be refactored/improved a bit in the upcoming weeks). Thanks for sharing the pointer to the external repo, we'll see if we can take some inspiration from it, to make sure the functionality is covered in this repo as well! 🙌

Thanks ! and deeply sorry to come back this late... feel free to check out what i've done...it works very well actually and does what it says

Perhaps you can use or re-use some of the code.

have a nice day !

[Import AWS To Localstackl](https://github.com/well-it-wasnt-me/Import-AWS-To-Localstack)
